version: '3.8'

services:
  web:
    build: .
    container_name: library-container
    restart: always
    env_file:
      - .env
    volumes:
      - ~/library-data:/app/data

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config: